logger: 
  project_name: "esaquand/bert"  
  run_id: None #GNN-106
  api_token: "eyJhcGlfYWRkcmVzcyI6Imh0dHBzOi8vYXBwLm5lcHR1bmUuYWkiLCJhcGlfdXJsIjoiaHR0cHM6Ly9hcHAubmVwdHVuZS5haSIsImFwaV9rZXkiOiJhZjRmODg1Yi0yZjVlLTQyOWYtOTk1Ny0wZGM0MmM5YzQ2NWQifQ=="
  description: ""
  prefix: "training"

data: 
  testing: false 
  hack: false

model: 
  model_name: "ClinicalBERT"
  fit: 
    resume_training: false
    ckpt_name: "epoch=0-step=4-val_loss=34285.29"
  predict: 
    result_folder: "results"
